-- =====================================================================
-- V1: Core schema for the local business discovery platform (MVP)
-- Compatible with PostgreSQL (Supabase) and H2 in PostgreSQL mode.
-- =====================================================================

CREATE TABLE profiles (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     VARCHAR(64)  NOT NULL UNIQUE,
    name        VARCHAR(150) NOT NULL,
    email       VARCHAR(255) NOT NULL,
    phone       VARCHAR(30),
    avatar_url  VARCHAR(512),
    role        VARCHAR(20)  NOT NULL DEFAULT 'CUSTOMER',
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE businesses (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id        VARCHAR(64)   NOT NULL,
    name            VARCHAR(150)  NOT NULL,
    category        VARCHAR(40)   NOT NULL,
    description     TEXT,
    phone           VARCHAR(30),
    whatsapp        VARCHAR(30),
    address         VARCHAR(255),
    address_number  VARCHAR(20),
    neighborhood    VARCHAR(120),
    city            VARCHAR(120),
    state           VARCHAR(60),
    postal_code     VARCHAR(20),
    latitude        DOUBLE PRECISION,
    longitude       DOUBLE PRECISION,
    cover_image_url VARCHAR(512),
    rating          DOUBLE PRECISION NOT NULL DEFAULT 0,
    total_reviews   INTEGER          NOT NULL DEFAULT 0,
    is_active       BOOLEAN          NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE business_services (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id      BIGINT        NOT NULL,
    name             VARCHAR(150)  NOT NULL,
    description      VARCHAR(500),
    price            NUMERIC(10,2),
    duration_minutes INTEGER,
    created_at       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_service_business FOREIGN KEY (business_id)
        REFERENCES businesses (id) ON DELETE CASCADE
);

CREATE TABLE business_images (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT        NOT NULL,
    image_url   VARCHAR(512)  NOT NULL,
    is_cover    BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_image_business FOREIGN KEY (business_id)
        REFERENCES businesses (id) ON DELETE CASCADE
);

CREATE TABLE business_hours (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id  BIGINT   NOT NULL,
    day_of_week  INTEGER  NOT NULL, -- 0 = Sunday ... 6 = Saturday
    opening_time VARCHAR(5),        -- 'HH:mm'
    closing_time VARCHAR(5),        -- 'HH:mm'
    is_open      BOOLEAN  NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_hours_business FOREIGN KEY (business_id)
        REFERENCES businesses (id) ON DELETE CASCADE,
    CONSTRAINT uq_hours_business_day UNIQUE (business_id, day_of_week)
);

CREATE TABLE reviews (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT       NOT NULL,
    user_id     VARCHAR(64)  NOT NULL,
    rating      INTEGER      NOT NULL,
    comment     VARCHAR(1000),
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_review_business FOREIGN KEY (business_id)
        REFERENCES businesses (id) ON DELETE CASCADE,
    CONSTRAINT uq_review_user_business UNIQUE (user_id, business_id),
    CONSTRAINT ck_review_rating CHECK (rating >= 1 AND rating <= 5)
);

CREATE TABLE favorites (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     VARCHAR(64)  NOT NULL,
    business_id BIGINT       NOT NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_favorite_business FOREIGN KEY (business_id)
        REFERENCES businesses (id) ON DELETE CASCADE,
    CONSTRAINT uq_favorite_user_business UNIQUE (user_id, business_id)
);

-- Indexes
CREATE INDEX idx_businesses_owner    ON businesses (owner_id);
CREATE INDEX idx_businesses_category ON businesses (category);
CREATE INDEX idx_businesses_active   ON businesses (is_active);
CREATE INDEX idx_businesses_geo      ON businesses (latitude, longitude);
CREATE INDEX idx_services_business   ON business_services (business_id);
CREATE INDEX idx_images_business     ON business_images (business_id);
CREATE INDEX idx_reviews_business    ON reviews (business_id);
CREATE INDEX idx_favorites_user      ON favorites (user_id);
