-- =====================================================================
-- V2: Management layer (multi-tenant). Each business (tenant) gains:
--   providers (profissionais), resources (recursos), appointments
--   (agendamentos) and inventory_items (estoque).
-- Compatible with PostgreSQL (Supabase) and H2 in PostgreSQL mode.
-- =====================================================================

CREATE TABLE providers (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT       NOT NULL,
    name        VARCHAR(150) NOT NULL,
    role        VARCHAR(100),            -- função/especialidade (ex: Barbeiro, Cabeleireira)
    phone       VARCHAR(30),
    avatar_url  VARCHAR(512),
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_provider_business FOREIGN KEY (business_id)
        REFERENCES businesses (id) ON DELETE CASCADE
);

CREATE TABLE resources (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT       NOT NULL,
    name        VARCHAR(150) NOT NULL,
    kind        VARCHAR(100),            -- tipo do recurso (ex: Cadeira, Sala, Estação)
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_resource_business FOREIGN KEY (business_id)
        REFERENCES businesses (id) ON DELETE CASCADE
);

CREATE TABLE appointments (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id   BIGINT       NOT NULL,
    appt_date     VARCHAR(10)  NOT NULL,  -- 'YYYY-MM-DD'
    appt_time     VARCHAR(5)   NOT NULL,  -- 'HH:mm'
    client_name   VARCHAR(150) NOT NULL,
    client_phone  VARCHAR(30),
    provider_id   BIGINT,
    resource_id   BIGINT,
    service_id    BIGINT,
    status        VARCHAR(20)  NOT NULL DEFAULT 'BOOKED', -- BOOKED | DONE | CANCELLED
    notes         VARCHAR(500),
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_appt_business FOREIGN KEY (business_id)
        REFERENCES businesses (id) ON DELETE CASCADE,
    CONSTRAINT fk_appt_provider FOREIGN KEY (provider_id)
        REFERENCES providers (id) ON DELETE SET NULL,
    CONSTRAINT fk_appt_resource FOREIGN KEY (resource_id)
        REFERENCES resources (id) ON DELETE SET NULL,
    CONSTRAINT fk_appt_service FOREIGN KEY (service_id)
        REFERENCES business_services (id) ON DELETE SET NULL
);

CREATE TABLE inventory_items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT       NOT NULL,
    name        VARCHAR(150) NOT NULL,
    kind        VARCHAR(20)  NOT NULL DEFAULT 'SUPPLY', -- SUPPLY (insumo) | RESALE (revenda)
    quantity    INTEGER      NOT NULL DEFAULT 0,
    min_quantity INTEGER     NOT NULL DEFAULT 3,         -- limiar de estoque baixo
    unit_price  NUMERIC(10,2),
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_inventory_business FOREIGN KEY (business_id)
        REFERENCES businesses (id) ON DELETE CASCADE
);

-- Indexes
CREATE INDEX idx_providers_business   ON providers (business_id);
CREATE INDEX idx_resources_business   ON resources (business_id);
CREATE INDEX idx_appointments_business ON appointments (business_id);
CREATE INDEX idx_appointments_provider ON appointments (provider_id);
CREATE INDEX idx_appointments_date     ON appointments (business_id, appt_date);
CREATE INDEX idx_inventory_business    ON inventory_items (business_id);
